export default{
  "login": "Veeresh603",
  "id": 57994727,
  "node_id": "MDQ6VXNlcjU3OTk0NzI3",
  "avatar_url": "https://avatars1.githubusercontent.com/u/57994727?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Veeresh603",
  "html_url": "https://github.com/Veeresh603",
  "followers_url": "https://api.github.com/users/Veeresh603/followers",
  "following_url": "https://api.github.com/users/Veeresh603/following{/other_user}",
  "gists_url": "https://api.github.com/users/Veeresh603/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Veeresh603/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Veeresh603/subscriptions",
  "organizations_url": "https://api.github.com/users/Veeresh603/orgs",
  "repos_url": "https://api.github.com/users/Veeresh603/repos",
  "events_url": "https://api.github.com/users/Veeresh603/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Veeresh603/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Veeresh",
  "company": 'Analogica Pvt Ltd',
  "blog": "",
  "location": "Bangalore",
  "email": null,
  "hireable": null,
  "bio": "React Js Web Developer ",
  "twitter_username": null,
  "public_repos": 12,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2019-11-20T13:19:10Z",
  "updated_at": "2020-09-16T07:53:08Z"
}